Completed JSX Parent Child Assignment
rajesh2355/zemoso_training pull request #11
Opened 2023-03-22 19:33 UTC by rajesh2355

2023-04-02 09:12 UTC, Sahithi-003 commented on React/jsx_assignment/src/Theme/index.tsx
> +      // shades of pink
Remove commented out part if not needed!

2023-04-02 09:12 UTC, Sahithi-003 commented on React/jsx_assignment/src/Theme/index.tsx
> +      //shades of black
Remove commented out part if not needed!

2023-04-02 09:12 UTC, Sahithi-003 commented on React/jsx_assignment/src/Theme/index.tsx
> +      //shades of gray(main) and white(light)
Remove commented out part if not needed!

2023-04-02 09:16 UTC, Sahithi-003 commented on React/jsx_assignment/src/stories/Examples/Button.stories.tsx
> +// More on args: https://storybook.js.org/docs/react/writing-stories/args
Remove commented code if not needed

2023-04-02 09:18 UTC, rajesh2355 commented
@Sahithi-003 I have updated the code Please check.

2023-04-03 03:54 UTC, Sahithi-003 commented on React/jsx_assignment/src/assets/Icons/info-circle.svg
Move icons to public folder and you can create atom icon

2023-04-03 03:55 UTC, Sahithi-003 commented on React/jsx_assignment/src/assets/Icons/receipt-item.svg
Move icons to public folder and you can create atom icon

2023-04-03 03:55 UTC, Sahithi-003 commented on React/jsx_assignment/src/components/Molecules/MidDiv/index.tsx
> +  width: 80px;
Dont hardcode width and heights concert them into vw and vh

2023-04-03 03:56 UTC, Sahithi-003 commented on React/jsx_assignment/src/components/Organisms/Card/index.tsx
> +  height: 260px;
Dont hardcode width and heights concert them into vw and vh

2023-04-03 03:58 UTC, Sahithi-003 requested changes
Your folder structure is not correct it should be like this
![image](https://user-images.githubusercontent.com/102959934/229408186-032ed628-e90a-4ba1-8b90-e1c427131cea.png)
Also please provide pr description appropriately!
Please address review comments!

2023-04-03 06:56 UTC, rajesh2355 commented on React/jsx_assignment/src/Theme/index.tsx
> +      // shades of pink
Changes done and pushed the updates.

2023-04-03 06:56 UTC, rajesh2355 commented on React/jsx_assignment/src/Theme/index.tsx
> +      //shades of black
changes done and pushed the updates.

2023-04-03 06:56 UTC, rajesh2355 commented on React/jsx_assignment/src/Theme/index.tsx
> +      //shades of gray(main) and white(light)
updated the code and pushed the changes.

2023-04-06 04:20 UTC, Sahithi-003 requested changes
Please keep only files that are to be reviewed and add all remaining to git ignore , Can't go through 68 files please make changes and update the pr

2023-04-06 09:51 UTC, rajesh2355 commented
@Sahithi-003 I have updated the files. Now this PR only contains the files which have been either added or modified.

2023-04-10 03:44 UTC, Sahithi-003 approved these changes

2023-04-10 03:55 UTC, merged